Features
Akorede3133/Hello-Microverse pull request #1
Opened 2023-05-31 11:11 UTC by Akorede3133

2023-05-31 12:00 UTC, usorfaitheloho requested changes
> Hi @Akorede3133  ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966) [ ](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## Highlights
> * All linter checks passed ✔️
> * Very good commit messages ✔️
> * Used GitHub flow ✔️
> 
> ## Required Changes ♻️
PLEASE EDIT YOUR PULL REQUEST TITLE AND SUMMARY SO IT DESCRIBE THE ACTIVITIES CARRIED OUT IN THIS MILESTONE 😺 

> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 12:00 UTC, usorfaitheloho commented on README.md
> + -->
Kindly remove all commented codes and description from your projects as they are meant to give you an explanation on what is required and shouldn't be part of your project 😄

2023-05-31 12:00 UTC, usorfaitheloho commented on README.md
> +--->
Kindly remove all commented codes and description from your projects as they are meant to give you an explanation on what is required and shouldn't be part of your project 😄

2023-05-31 12:00 UTC, usorfaitheloho commented on README.md
> +<!-- LICENSE -->
Kindly remove all commented codes and descriptions from your projects as they are meant to give you an explanation of what is required and shouldn't be part of your project 😄 , also remove the FAQ section since it's optional

2023-05-31 12:00 UTC, usorfaitheloho commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
Please add a license file to your project so that when the user clicks on it, it will take him/her to the copyright file for your project 😄

2023-05-31 12:00 UTC, usorfaitheloho commented on index.html
> +    <h1>Hello Microverse!</h1>
According to the project requirement, you're to add a class property in your `h1` tag and style the class in your CSS file. kindly implement this for best HTML and CSS practices 😄 

Requirement
![image](https://github.com/Akorede3133/Hello-Microverse/assets/20537712/3e826d71-af58-4ce3-a195-bcd0284b45d0)

2023-05-31 13:12 UTC, usorfaitheloho requested changes
> Hi @Akorede3133  ,
> 
> Great job for implementing  some of the Project Requirement, but there are some changes that need to be implemented in order to proceed to the next project 👍
> 
> ## Highlights 👏🏻
> ✔️ No linters error ✔️ You used correct Git Hub-Flow. ✔️ Good README ✔️ Good Commit Messages
> 
> ![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif) 

> ## Required Changes ♻️
> _Check the comments below the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 13:12 UTC, usorfaitheloho commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
You did well to implement the changes suggested . As suggested previously, kindly add a `LICENSE` file to your project directory to enable a user to get a copyright file for your project 😄

2023-05-31 14:18 UTC, V-Blaze approved these changes
Hi @Akorede3133  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Correct GitHub flow💯
-  Linters setup correctly👍
-  Readme looks professional 🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 08:14 UTC, Akorede3133 commented
Merging to the main branch to the feature branch

2023-06-01 08:14 UTC, merged

2023-06-23 10:01 UTC, topeogunleye commented
Hi @Akorede3133, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted the wrong PR from the `Hello Microverse project` to be reviewed as `Activity name: Portfolio: details popup window`.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._